### ISSUE TITLE
Window interception in Mac OS X not reliable

### ISSUE THREAD

**Issue by falkoschumann** [UISpec4J/UISpec4J#20]
In Mac OS X 10.10.3 and Java 8 Update 45 the window interception works not reliable. My main method create and and initialize a JFrame and make it visible. The interception of this Window works only every second time. I get this exception

```
java.lang.AssertionError: No window was shown (timeout expired)
    at org.junit.Assert.fail(Assert.java:88)
    at org.uispec4j.assertion.testlibrairies.JUnitLibrary.fail(JUnitLibrary.java:7)
    at org.uispec4j.assertion.testlibrairies.AssertAdapter.fail(AssertAdapter.java:11)
    at org.uispec4j.interception.handlers.ShownInterceptionDetectionHandler.waitWindow(ShownInterceptionDetectionHandler.java:39)
    at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:324)
    at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:290)
    at org.uispec4j.interception.MainClassAdapter.getMainWindow(MainClassAdapter.java:24)
```

In Windows 7 and Linux both with Java 8 Update 45, the window interception works perfectly.

In Mac OS X 10.10, if I wrap JFrame initialization in SwingUtilities.invokeLater() I get the timeout average every second time. If I wrap JFrame initialization in SwingUtilities.invokeAndWait() the window is intercepted every time.

I solve this issue using invokeAndWait in main method. But should it works with invokeLater() also?

**Comment by nebulorum** [comment]
I agree with you, as long as it's the AWT Event Thread it should work. I think with more cores around we are hitting some race conditions. Can you give me sample code or point to the code in question so I can investigate?

**Comment by falkoschumann** [comment]
This is a customer project so it's not open source. But I try to reproduce the issue with a example project. Give me a some time.

**Comment by falkoschumann** [comment]
If this is a race condition, I can it not reproduce with a simple JFrame. I added Hibernate to reproduce it. Here is the demo project https://github.com/falkoschumann/uispec4j-issue20.

The demo shows the issue not as reliable as the original project. But if I set a breakpoint to marked method in Main.java, the issue happens often.

I hope it helps.

**Comment by nebulorum** [comment]
Thanks for the sample code. I'm not very familiar with Hibernate, but I'd assume it have its own thread pools and execution contexts. That may indeed be working together. Do you ever see a problem on the actual system?

I'll try to see if I can figure out where there is a race condition. But this may take a while. 

Here are some ideas, if this is Integration test, maybe having the Hibernate outside of main as a service could push initialization code outside of the Swing space.

If this is just a GUI test in isolation, I code you could think of using Model - View - Presenter model. Have the GUI do just View and Presenter and test that. Hibernate feeds the presenter, which is tested without using UISpec4J. GWT has some example on how to do this.

**Comment by falkoschumann** [comment]
I upgrade Hibernate from version 3.x to 4.x recently. Indeed I discover a new thread, which did not exist previously. Also I upgrade UISpec4J from 2.4 to 2.5, because the upgrade from Java 6 to 8.

I use UISpec4J as well with unit tests as with integration tests. In the unit tests Hibernate is replaced by stub. A unit is a form actually a form controller. UISpec4J is acting as view mock. In integration tests the whole set of forms in the application is under test. In this situation hibernate use a memory database instead of production database.

There are no problems under Windows and Linux, only Mac OS X show this issue. I solve the problem for the moment, as described above.

Hibernate should not initialized in event dispatch thread. I found this fact, reducing the real application to reproduce the issue with minimal code. In real application a set of factories create the GUI and initialize services like Hibernate. I will rewrite the code to better separate initialization GUI and non GUI.

**Comment by howardphi** [comment]
I'm also experiencing similar issues with window interception on macOS (using IntelliJ) - sometimes mvn test works, sometimes not. It's very inconsistent.

-------------------------------------------------------------------------------
Test set: xxx
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.314 sec <<< FAILURE!
testAddingAndDeletingAccount(xxx)  Time elapsed: 10.023 sec  <<< FAILURE!
java.lang.AssertionError: No window was shown (timeout expired)
	at org.junit.Assert.fail(Assert.java:93)
	at org.uispec4j.assertion.testlibrairies.JUnitLibrary.fail(JUnitLibrary.java:7)
	at org.uispec4j.assertion.testlibrairies.AssertAdapter.fail(AssertAdapter.java:11)
	at org.uispec4j.interception.handlers.ShownInterceptionDetectionHandler.waitWindow(ShownInterceptionDetectionHandler.java:39)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:324)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:290)
	at org.uispec4j.interception.MainClassAdapter.getMainWindow(MainClassAdapter.java:24)
	at org.uispec4j.UISpecTestCase.getMainWindow(UISpecTestCase.java:84)
	at ca.etsmtl.log240.financej.FinancejAbstractTest.setUp(FinancejAbstractTest.java:28)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
