### ISSUE TITLE
Cannot find symbol getDataTransferer() on JDK 8

### ISSUE THREAD

**Issue by SQUIDwarrior** [UISpec4J/UISpec4J#22]
When I try and run the tests using JDK 8 on Windows, I get a "cannot find symbol" error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project uispec4j: Compilation failure
[ERROR] /C:/Users/ct626c/workspace/UISpec4J/uispec4j/src/main/java-jdk8/org/uispec4j/interception/toolkit/ToolkitDelegate.java:[131,20] cannot find symbol
[ERROR] symbol:   method getDataTransferer()
[ERROR] location: class sun.awt.SunToolkit
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project uispec4j: Compilation failure
/C:/Users/ct626c/workspace/UISpec4J/uispec4j/src/main/java-jdk8/org/uispec4j/interception/toolkit/ToolkitDelegate.java:[131,20] cannot find symbol
  symbol:   method getDataTransferer()
  location: class sun.awt.SunToolkit

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by SQUIDwarrior** [comment]
Forgot to put my Java version too:

    java version "1.8.0_11"
    Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

**Comment by nebulorum** [comment]
Are you using the JDK8 classifier on your build? This happens when you use the wrong classifier.

**Comment by SQUIDwarrior** [comment]
I ran this command exactly, per the instructions in the "README"

    mvn -Pjdk8 -Dgpg.skip=true clean install

**Comment by nebulorum** [comment]
Are you trying to build it or use it in your project. In your project I'd use 2.5-RC1 that is on Maven central. You need to add the classifier.

**Comment by SQUIDwarrior** [comment]
I am just trying to build UISpec4j for use in my other project that does not use Maven. I need to create a jar file with the updated UISpec4j code to include in that project's classpath.

This was on Windows. I tried the same thing on my Ubuntu VM and the compile worked fine, but I get a hang when it tries to run the tests and eventually it times out.

**Comment by nebulorum** [comment]
I'll have to setup some environment for this.  I've seen some hangs on my Travis CI. But that was on a headless setup.

Have you tested the version on Maven Central?

**Comment by SQUIDwarrior** [comment]
No, but I will do some experimenting with it today.

**Comment by SQUIDwarrior** [comment]
Ok, it seems the jars on Maven Central work fine with my JUnit tests on Linux. Still not sure why I can't build from source, but it looks like this will work.

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
