### ISSUE TITLE
WindowInterceptorForModalDialogsTest is unstable

### ISSUE THREAD

**Issue by bramblevine** [UISpec4J/UISpec4J#23]
I've been investigating an issue in my copmany CI environment. It's showing builds with inconsistent results which we first thought was related to using a 64bit JDK 7 version but we've since reproduced the issue on the 32bit versions as well. 

Whilst attempting to build the latest version of UISpec4J I noticed that the modal dialog test  WindowInterceptorForModalDialogsTest has inconsistent results. Particularly when run directly from Idea. Some runs pass, some fail tests with a no window shown error and others hang on the testInterceptingAJDialogShownFromAnotherThread test. A stacktrace shows the test is hanging on the Thread.join() in the teardown whilst another thread is waiting on the modal dialog show method call.

```
"Thread-2" prio=10 tid=0xab31ac00 nid=0x3793 in Object.wait() [0xab1ba000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0xde1ee438> (a java.awt.Component$AWTTreeLock)
        at java.lang.Object.wait(Object.java:503)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:247)
        - locked <0xde1ee438> (a java.awt.Component$AWTTreeLock)
        at java.awt.Dialog.show(Dialog.java:1082)
        at org.uispec4j.interception.WindowInterceptorForModalDialogsTest$8$1.run(WindowInterceptorForModalDialogsTest.java:174)

"main" prio=10 tid=0xf6608400 nid=0x376e in Object.wait() [0xf6796000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0xde5556c8> (a org.uispec4j.interception.WindowInterceptorForModalDialogsTest$8$1)
        at java.lang.Thread.join(Thread.java:1280)
        - locked <0xde5556c8> (a org.uispec4j.interception.WindowInterceptorForModalDialogsTest$8$1)
        at java.lang.Thread.join(Thread.java:1354)
        at org.uispec4j.interception.WindowInterceptorForModalDialogsTest.tearDown(WindowInterceptorForModalDialogsTest.java:21)
```

It happens with all the JDK versions I've tried, 6, 7 and 8 and appears similar to the problems showing up on the [travis CI builds](https://travis-ci.org/UISpec4J/UISpec4J/builds/58008762)

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
