### ISSUE TITLE
FileChooserHandler not intercepting JFileChooser

### ISSUE THREAD

**Issue by liscju** [UISpec4J/UISpec4J#24]
I cannot intercept JFileChooser no matter what i do , the simplest test case to recreate the problem is:

``` java
import org.junit.Test;
import org.uispec4j.Trigger;
import org.uispec4j.UISpecTestCase;
import org.uispec4j.interception.FileChooserHandler;
import org.uispec4j.interception.WindowInterceptor;

import javax.swing.*;

public class FileChooserHandlerTest extends UISpecTestCase {

    @Test
    public void testSimpleJFileChooserTest() throws Exception {
        WindowInterceptor
                .init(new Trigger() {
                    @Override
                    public void run() throws Exception {
                        JFrame frame = new JFrame();
                        new JFileChooser().showOpenDialog(frame);
                    }
                })
                .process(FileChooserHandler.init().cancelSelection())
                .run();
    }
}
```

Running ends with:

```

org.uispec4j.interception.InterceptionError: No window was shown (timeout expired)
    at com.puppycrawl.tools.checkstyle.gui.FileChooserHandlerTest.testMainFrameOnCancelFileSelectionDoNothing(FileChooserHandlerTest.java:24)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.AssertionError: No window was shown (timeout expired)
    at org.junit.Assert.fail(Assert.java:88)
    at org.uispec4j.assertion.testlibrairies.JUnitLibrary.fail(JUnitLibrary.java:7)
    at org.uispec4j.assertion.testlibrairies.AssertAdapter.fail(AssertAdapter.java:11)
    at org.uispec4j.interception.handlers.ShownInterceptionDetectionHandler.waitWindow(ShownInterceptionDetectionHandler.java:39)
    at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:347)
    at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:200)
    ... 23 more

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0

Process finished with exit code -1

```

My configuration:
OS: Windows 8 64-Bit
SDK: Java 1.8.0_40 64-Bit
Run from: Intellij Idea 14.1

**Comment by nebulorum** [comment]
What version are you using? 2.5R1?

**Comment by liscju** [comment]
@nebulorum yes

**Comment by nebulorum** [comment]
Is this test brand new? Has it ever worked? Are you using the JDK8 classifier?

**Comment by liscju** [comment]
I didn't checked this test case on earlier version of UISpec4J because with version 2.4 i ran into problem described here:
http://stackoverflow.com/questions/20639170/uispec4j-abstractmethoderror-uispectoolkit-createkeyboardfocusmanagerpeer

With version 2.5R1 problem with abstract method error is gone and library for other things (such as getting text from button, reading title of window etc..) works fine. 

Considering last question: i think so because in project structure JDK8 is chosen as JDK but i have no idea how to check this.

**Comment by nebulorum** [comment]
UISpec4J comes with several classifiers normally on Maven this is one of the option on the dependency. Select the correct one for you JDK and it will work. However if you are pointing to the version directly you should use the `uispec4j-2.5-RC1-jdk8.jar` file.

**Comment by liscju** [comment]
Thank you very much,test case is working now. I have two additional issues - first of all in project i want to use uispec4j we support JDK6,JDK7,JDK8 in development - how can we choose specifier to works in any of those JDK? 

Secondly ,even though test case is running i still have problem with my original code. I invoke it like this:

```java
    @Test
    public void testMainFrameOnProperlySelectedEmptyFileLoadIt() throws Exception {
        Window mainWindow = getMainWindow();
        Button loadFile = mainWindow.getButton("LoadFile");
        ClassLoader classLoader = getClass().getClassLoader();
        File fileToSelect =
                new File(classLoader.getResource("EmptyClass.java").getFile());
        WindowInterceptor
                .init(loadFile.triggerClick())
                .process(FileChooserHandler.init().select(fileToSelect))
                .run();
    }
```

Where mainWindow is properly initialized, loadFile is proper too because given button is on the form and fileToSelect is correct also. LoadFile button on main window has action like this:

```java
private class FileSelectionAction extends AbstractAction {
        /**
         * Serial ID.
         */
        private static final long serialVersionUID = -1926935338069418119L;

        /** Defalut constructor to setup current action. */
        FileSelectionAction() {
            super("Select Java File");
            putValue(Action.MNEMONIC_KEY, KeyEvent.VK_S);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            final JFileChooser fc = new JFileChooser(lastDirectory);
            final FileFilter filter = new JavaFileFilter();
            fc.setFileFilter(filter);
            final Component parent =
                SwingUtilities.getRoot(ParseTreeInfoPanel.this);
            fc.showDialog(parent, "Open");
            final File file = fc.getSelectedFile();
            openFile(file, parent);

        }
    }
```

Everything seems correct except that it fails with:

```
org.uispec4j.interception.InterceptionError: null
	at com.puppycrawl.tools.checkstyle.gui.ParseTreeInfoPanelITTest.testMainFrameOnProperlySelectedEmptyFileLoadIt(ParseTreeInfoPanelITTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
	at org.uispec4j.utils.TriggerRunner.runInSwingThread(TriggerRunner.java:27)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:346)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:200)
	at com.puppycrawl.tools.checkstyle.gui.ParseTreeInfoPanelITTest.testMainFrameOnProperlySelectedEmptyFileLoadIt(ParseTreeInfoPanelITTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
	at com.puppycrawl.tools.checkstyle.gui.ParseTreeInfoPanel.openFile(ParseTreeInfoPanel.java:157)
	at com.puppycrawl.tools.checkstyle.gui.ParseTreeInfoPanel$FileSelectionAction.actionPerformed(ParseTreeInfoPanel.java:385)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at org.uispec4j.AbstractButton.doClick(AbstractButton.java:37)
	at org.uispec4j.AbstractButton.click(AbstractButton.java:26)
	at org.uispec4j.AbstractButton$3.run(AbstractButton.java:78)
	at org.uispec4j.utils.TriggerRunner.runInCurrentThread(TriggerRunner.java:12)
	at org.uispec4j.utils.TriggerRunner$1.run(TriggerRunner.java:32)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option UseSplitVerifier; support was removed in 8.0
```

Maybe i did sth in test case so wrong that it can be easily  pointed by you? Of course if not i will create simple test case for this.

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
