### ISSUE TITLE
Error while setting look and feel

### ISSUE THREAD

**Issue by kameshakr** [UISpec4J/UISpec4J#26]
Hi, I am new to UISpec4J, 
We are planing to write GUI automation and trying to evaluate how well this library fits into our existing design.
I was able to successfully get the lib dependency and execute a sample test case and all look good. I was impressed with easy of setting it up and running a sample test case on a Basic JFrame. But when I was trying to launch our app, I am unable to get through to the main window as it is throwing number of exceptions.
Initial difficulty for me is that it fails while process the code where the app is trying to set look and feel. We use the synthetica look and feel for our app. 
Here is the stack trace for the error
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
    at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:281)
    at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1012)
    at javax.swing.JComponent.getFontMetrics(JComponent.java:1624)
    at de.javasoft.plaf.synthetica.styles.TableStyle.get(TableStyle.java:73)
    at de.javasoft.plaf.synthetica.SyntheticaLookAndFeel.installCompatibilityDefaults(SyntheticaLookAndFeel.java:1122)
    at de.javasoft.plaf.synthetica.SyntheticaLookAndFeel.setFont(SyntheticaLookAndFeel.java:1508)
    at de.javasoft.plaf.synthetica.StyleFactory.getStyle(StyleFactory.java:347)
    at de.javasoft.plaf.synthetica.StyleFactory.getStyle(StyleFactory.java:238)
    at de.javasoft.plaf.synthetica.SyntheticaLookAndFeel.installCompatibilityDefaults(SyntheticaLookAndFeel.java:973)
    at de.javasoft.plaf.synthetica.SyntheticaLookAndFeel$4.propertyChange(SyntheticaLookAndFeel.java:702)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at javax.swing.UIManager.setLookAndFeel(UIManager.java:545)
    at javax.swing.UIManager.setLookAndFeel(UIManager.java:580)

Can you please let me know if there is something which I should do to avoid/circumvent this?

Also along way I am finding Null Pointer Exceptions when the app making calls to dispose some panels on the screen and while getting the borders of some components and some other calls to swing components methods

Can you please share your thoughts if this is supported and could be handled?

Many thanks in advance!!!

**Comment by nebulorum** [comment]
I'm not sure what is the issue here. One thing to be aware of is that UISpec4J will not show the Swing objects. So if the LAF is using real device data on object that are being mocked or replaced by dummies you can run into problem. It also can handle Focus changes.

I personally use UISpec4J to test the general logic and wiring of my Swing code but not the appearance of the final GUI. So I'd suggest disabling the LAF and running tests without that layer. Of course if you are using LAF extension to behavior this may be tricky.

**Comment by kameshakr** [comment]
Thanks Tomas, It look likes it is problem with Custom look and feel, I was able to run the app when the LAF is not set.. However I don't have control on external app, so have to figure out a way to do test while LAF is set

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
