### ISSUE TITLE
ClassCastException  org.uispec4j.interception.toolkit.Empty$DummyGraphics2D cannot be cast to sun.java2d.SunGraphics2D

### ISSUE THREAD

**Issue by adamish** [UISpec4J/UISpec4J#31]
java.lang.ClassCastException: org.uispec4j.interception.toolkit.Empty$DummyGraphics2D cannot be cast to sun.java2d.SunGraphics2D
    at java.awt.Component$BltBufferStrategy.getDrawGraphics(Component.java:4348)
    at javax.swing.BufferStrategyPaintManager.prepare(BufferStrategyPaintManager.java:522)
    at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:276)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1265)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5167)
    at javax.swing.JComponent.paintImmediately(JComponent.java:4978)
    at javax.swing.JComponent.paintImmediately(JComponent.java:4990)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:371)

Also I asked on SO 

http://stackoverflow.com/questions/42882626/classcastexception-using-uispec4j

**Comment by nebulorum** [comment]
Closing, if still relevant please reopen.
