### ISSUE TITLE
UISpec4J for Java 17

### ISSUE THREAD

**Issue by gonnot** [UISpec4J/UISpec4J#40]
Hi UISpec4J,

In my company, we use UISpec4J a lot for our Swing projects. As we are moving from Java 8 to Java 17, we had to update UISpec4J (making it compatible with jigsaw). For our own purposes, we plan to maintain the library to match the "semi-annual cadence" of the JDK delivery.

If anyone is interested, we can create a pull request and participate in the life of the library.

Regards.

**Comment by nebulorum** [comment]
I could try to recover the build and deploy process. I think I still have access to it. The main challenge is that it's been a long time since I've tried to use it. And some of the JVM changes were making some tests flaky.

**Comment by Minothor** [comment]
Hi @nebulorum is there any update on this?
I'm using a tweaked version of @gonnot's fork (preventing Junit5 deps from propagating into downstream POMs) in order to write the test coverage we need for various UI elements in iText RUPS but the lack of official maven release means that a fair few of the UI improvements I'm working on can't be pushed to the repo here on GitHub for open-sourcing.

We're currently having to implement this by hosting the forked version in our build system but we'd prefer to have the repository buildable by the public at large.

Is there any new information regarding this or any way in which I can help with it?

**Comment by nebulorum** [comment]
@Minothor I have to apologize. I haven't used this project in a long time and don't even have how to build and test. 

However if you are actively using it I can attempt to merge and release. I did try to build automated builds but that was year ago. Do you have the link to the PR? Also what has been your testing strategy?

**Comment by gastendonk** [comment]
I released a built version of my fork via jitpack.io. https://github.com/gastendonk/uispec4j

**Comment by nebulorum** [comment]
@gastendonk it has been years since I have released a version. I'm not sure on the maturity, but I you help recover the build process I can try to recover my ability to push to central repo and we could do a new release. What do you think?

**Comment by gastendonk** [comment]
@nebulorum 
I can try to send you a Java 17 pull request based on  @gonnot 's and my work the next days. And I would appreciate it if you could do an official release (2.6? 3.0?) afterwards.

**Comment by gastendonk** [comment]
@nebulorum 

I've incorporated gonnot's and my work into my fork from the original repository. https://github.com/gastendonk/UISpec4J_original

version 3.0-SNAPSHOT

I have removed the website as I feel it no longer exists.

I will test the library and then I will submit a PR.

**Comment by gastendonk** [comment]
I built it and tested it in my project. It works.

I'm not a Maven expert. I can't run the unit tests in Eclipse or with Maven. I need help from you! Error in pom.xml?

```
WARNING: Unknown module: org.junit.platform.commons specified to --add-opens
Class not found org.uispec4j.utils.ArrayUtilsTest
java.lang.ClassNotFoundException: org.uispec4j.utils.ArrayUtilsTest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:766)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:490)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by nebulorum** [comment]
I managed to get most of it working on JDK11. Still struggling with the extension any chance you merge back? I'm willing to try a 2.5 on the new version.

**Comment by gastendonk** [comment]
> any chance you merge back?

No, I won't do anything.

**Comment by nebulorum** [comment]
Are you using your branch in projects? If so and it happpens to be open source it would be a great test bed. I could then try to get the official version out.

**Comment by gastendonk** [comment]
> Are you using your branch in projects?

We use https://github.com/gastendonk/UISpec4J_original/commits/master/ (branch: master) daily in our non open source project. Almost 1500 testcases are executed every night. Of course we don't cover 100% of the uispec4j features.

If you would release a 2.5-beta1 or 2.5-rc1, I could test it with our software.
